environments:
  ldap_hooks:
    environments:
      GIT_USER: "{{SECRET:[github][username]}}"
      PYPI_USERNAME: "{{SECRET:[ldap_hooks][username]}}"
      PYPI_PASSWORD: "{{SECRET:[ldap_hooks][password]}}"
      TEST_VAR: asdadaD
    pipelines:
      - ldap_hooks
pipelines:
  ldap_hooks:
    group: bare_metal_pypi_package
    locking: off
    timer:
      # Run on the 1st at 00:00 of every month
      spec: "0 0 0 1 * ? *"
      only_on_changes: no
    materials:
      ldap_hooks_git:  # this is the name of material
        # says about type of material and url at once
        git: https://github.com/ucphhpc/ldap_hooks.git
        branch: master
        destination: ldap_hooks
      publish_python_git:
        git: https://github.com/rasmunk/publish-python-scripts.git
        branch: main
        username: ${GIT_USER}
        password: "{{SECRET:[github][access_token]}}"
        destination: publish-python-scripts
    parameters:
      ARGS: ''
      SRC_DIRECTORY: ldap_hooks
      TEST_DIRECTORY: ldap_hooks
      PUSH_DIRECTORY: publish-python-scripts
    template: bare_metal_pypi_package
